var assert = require('assert');
var fs = require('fs');
var path = require('path');

var root = path.resolve(__dirname, '..');
var cloud = fs.readFileSync(path.join(root, 'cloudfunctions/tradeData/index.js'), 'utf8');
var page = fs.readFileSync(path.join(root, 'miniprogram/pages/review/index.js'), 'utf8');
var template = fs.readFileSync(path.join(root, 'miniprogram/pages/review/index.wxml'), 'utf8');
var chart = fs.readFileSync(path.join(root, 'miniprogram/components/trend-chart/index.js'), 'utf8');

assert.ok(cloud.indexOf('periodDefinition') !== -1);
assert.ok(cloud.indexOf("period_type: 'week'") !== -1);
assert.ok(cloud.indexOf("action === 'getPeriodReview'") !== -1);
assert.ok(cloud.indexOf("METRICS: 'period_metrics'") !== -1);
assert.ok(cloud.indexOf('Math.round(planned.length / events.length * 100)') !== -1, 'discipline score must count only explicitly planned events');
assert.strictEqual(cloud.indexOf('(events.length - impulsive.length) / events.length'), -1, 'uncertain events must not count as planned');
assert.ok(cloud.indexOf('current_focus: command.set(focus)') !== -1, 'weekly focus should replace the legacy string value atomically');
assert.ok(cloud.indexOf("action === 'getPeriodDetail'") !== -1, 'period metrics should expose matching trade details');
assert.ok(cloud.indexOf('reasonDistributionReady: events.length >= 5') !== -1, 'reason distribution must wait for a useful sample');
assert.ok(cloud.indexOf('buildChangeClue') !== -1, 'multi-period changes should be phrased as clues');
assert.ok(page.indexOf("periodType: 'week'") !== -1);
assert.ok(page.indexOf('switchPeriod') !== -1);
assert.ok(template.indexOf('周复盘') !== -1);
assert.ok(template.indexOf('月复盘') !== -1);
assert.ok(template.indexOf('trend-chart') !== -1);
assert.ok(template.indexOf('再积累一个有操作的周期') !== -1);
assert.ok(template.indexOf('trend-card--compact') !== -1);
assert.ok(page.indexOf('trendReady: activePoints.length >= 2') !== -1);
assert.ok(page.indexOf('trendPointsJson: JSON.stringify(data.trend || [])') !== -1);
assert.ok(page.indexOf('toggleTrend') !== -1);
assert.ok(page.indexOf('selectTrendPeriod') !== -1, 'trend points should open historical periods');
assert.ok(page.indexOf('openMetricDetail') !== -1, 'summary metrics should drill into matching records');
assert.ok(chart.indexOf("pointsJson: { type: String") !== -1);
assert.ok(chart.indexOf("compact: { type: Boolean") !== -1);
assert.ok(chart.indexOf('handleTap') !== -1);
assert.ok(chart.indexOf("triggerEvent('select', point)") !== -1);
assert.ok(chart.indexOf("ctx.setStrokeStyle('#2D8065')") !== -1);
assert.ok(template.indexOf('常见操作原因') !== -1);
assert.ok(template.indexOf('变化线索') !== -1);

console.log('period review tests passed');
