const assert=require('assert'),fs=require('fs'),path=require('path');
let definition;
global.Component=d=>definition=d;
require('../miniprogram/components/trend-chart/index');
const points=[{periodId:'empty',value:null},{periodId:'zero',value:0},{periodId:'full',value:100}];
let selected;
const chart={properties:{interactive:true},data:{},_chartPoints:points,_chartRect:{left:100,width:216},triggerEvent:(name,p)=>selected=p.periodId,setData(p){Object.assign(this.data,p);}};
Object.assign(chart,definition.methods);
chart.selectPoint({currentTarget:{dataset:{index:0}}});assert.equal(selected,undefined);
chart.selectPoint({currentTarget:{dataset:{index:1}}});assert.equal(selected,'zero');
chart.handleTap({detail:{x:308},changedTouches:[{clientX:208}]});assert.equal(selected,'zero');
chart.handleTap({detail:{x:308}});assert.equal(selected,'full');
chart.properties.interactive=false;chart.selectPoint({currentTarget:{dataset:{index:1}}});assert.equal(selected,'full');
let queryCalls=0,queryCallback;
chart.createSelectorQuery=()=>{queryCalls++;const q={select(){return q;},boundingClientRect(){return q;},fields(o){assert(o.node);return q;},exec(fn){queryCallback=fn;}};return q;};
chart.properties.suspended=true;chart._draw(points);assert.equal(queryCalls,0);
chart.properties.suspended=false;chart._draw(points);assert.equal(queryCalls,1);
chart.properties.suspended=true;queryCallback([{width:216,height:100},{node:{getContext(){throw Error('draw after suspension');}}}]);
chart.properties.suspended=false;chart._detached=true;chart._draw(points);assert.equal(queryCalls,1);
const markup=fs.readFileSync(path.join(__dirname,'../miniprogram/components/trend-chart/index.wxml'),'utf8');
assert(markup.includes('type="2d"'));assert(!markup.includes('canvas-id='));
assert(/<image[^>]*src="{{imageSrc}}"/.test(markup),'visible chart must be a page image');
assert(/<canvas[^>]*class="trend-chart__renderer"/.test(markup),'drawing canvas must remain separate from the visible chart');
const css=fs.readFileSync(path.join(__dirname,'../miniprogram/components/trend-chart/index.wxss'),'utf8');assert(css.includes('top:-10000px'));
const drawCalls=[];let contexts=0,exportCalls=[];
const ctx={scale:(x,y)=>drawCalls.push(['scale',x,y]),clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fill(){},closePath(){},arc:(x,y,r)=>drawCalls.push(['arc',x,y,r]),createLinearGradient:()=>({addColorStop(){}})};
const canvas={getContext:type=>{assert.equal(type,'2d');contexts++;return ctx;}};
global.wx={getWindowInfo:()=>({pixelRatio:3}),canvasToTempFilePath:o=>exportCalls.push(o)};
chart._detached=false;chart._hidden=false;chart.properties.compact=false;chart._drawVersion=4;
function render(){queryCallback([{left:100,top:20,width:216,height:100},{node:canvas}]);}
chart._draw(points,4);render();assert.equal(canvas.width,648);assert.equal(canvas.height,300);assert.deepEqual(drawCalls[0],['scale',3,3]);assert.equal(chart._validPoints.length,2);
exportCalls[0].success({tempFilePath:'chart-1.png'});assert.equal(chart.data.imageSrc,'chart-1.png');
chart._draw(points,4);render();assert.equal(contexts,2);assert.equal(drawCalls.filter(c=>c[0]==='scale').length,2);
chart._cancelDraw();exportCalls[1].success({tempFilePath:'stale.png'});assert.equal(chart.data.imageSrc,'chart-1.png','stale export cannot replace current image');
chart._draw(points,chart._drawVersion);chart._cancelDraw();render();assert.equal(contexts,2,'stale query must not draw');
chart._draw(points,chart._drawVersion);definition.pageLifetimes.hide.call(chart);render();assert.equal(contexts,2,'hidden page must not draw');
chart._hidden=false;chart._draw(points,chart._drawVersion);render();exportCalls[2].fail();assert(chart.data.chartFailed,'export failure offers retry');
console.log('Trend chart: image-layer presentation, DPR, null/zero points, touch selection, suspension, stale query/export cancellation and export failure passed');
