const assert=require('assert'),fs=require('fs'),vm=require('vm');
const tick=()=>new Promise(setImmediate);
function load(file,deps,extras,kind='Page'){let d;vm.runInNewContext(fs.readFileSync('miniprogram/'+file,'utf8'),Object.assign({[kind]:x=>d=x,require:deps,console,setTimeout,clearTimeout},extras));return d;}
function instance(d){return Object.assign({data:JSON.parse(JSON.stringify(d.data)),setData(p,cb){Object.assign(this.data,p);if(cb)cb();}},d.methods||d);}
const event=(key,value)=>({currentTarget:{dataset:{[key]:value}}});
(async()=>{
 let writes=0,reads=0,modals=0,revision=0;const nav=[];
 const app={getPageRevision:()=>revision,waitForLogin:()=>Promise.resolve(),invalidatePages:()=>revision++,globalData:{}};
 const wx={hideKeyboard(){},showToast(){},navigateTo:o=>nav.push(o.url),showModal(){modals++;},setStorageSync(){},getStorageSync(){},pageScrollTo(){},setNavigationBarTitle(){}};
 const base=n=>n.includes('share')?{enable(){}}:n.includes('constants')?{STORAGE_KEYS:{RECORD_DRAFT:'draft'},ROUTES:{REFLECTION:'/detail'}}:{};
 const record=instance(load('pages/record/index.js',base,{wx,getApp:()=>app}));record.chooseSymbol(event('symbol','RKLB'));assert.equal(record.data.step,2);assert.equal(record.data.symbol,'RKLB');record.chooseSymbol(event('symbol','IBM'));assert.equal(record.data.symbol,'RKLB','second tap cannot replace symbol after advancing');record.previousStep();assert.equal(record.data.step,1);
 const reflection=instance(load('pages/reflection/index.js',n=>n.includes('trade-service')?{markExecution:()=>{writes++;return Promise.resolve({success:true});}}:base(n),{wx,getApp:()=>app}));reflection._loadEvent=()=>{};reflection.data.event={execution_status:'pending'};reflection.confirmExecution(event('status','executed'));reflection.confirmExecution(event('status','executed'));assert.equal(writes,1);assert.equal(modals,0);await tick();
 const bar={data:{hidden:false},setData(p){Object.assign(this.data,p);}};
 let sourceReads=0;
 const relatedD=load('components/related-history/index.js',()=>({getHistory:()=>{sourceReads++;return Promise.resolve({success:true,data:{count:0,items:[],hasMore:false}});}}),{wx,getApp:()=>app,getCurrentPages:()=>[{getTabBar:()=>bar}]},'Component');
 const related=instance(relatedD);related.data.sheetOnly=true;related.data.source={_id:'r'};relatedD.lifetimes.attached.call(related);relatedD.pageLifetimes.show.call(related);assert.equal(sourceReads,0);related.open();assert(related.data.visible);assert(bar.data.hidden);await tick();assert.equal(sourceReads,1);assert(related.data.checked);related.close();assert(!bar.data.hidden);related.open();await tick();assert.equal(sourceReads,1,'opening a current empty result does not reload');related.close();revision++;related.open();await tick();assert.equal(sourceReads,2,'record changes invalidate the sheet');related.invalidate();assert(!related.data.visible);assert(!related.data.checked);assert(!bar.data.hidden);
 let saveCalls=0,resolveSave;
 const supplement=instance(load('components/optional-supplement/index.js',n=>n.includes('attachment')?{MAX_IMAGE_COUNT:3,cleanup(){}}:{call:()=>{saveCalls++;return new Promise(r=>resolveSave=r);}}, {wx},'Component'));
 supplement.properties={entityType:'trade_event',entityId:'r',note:'old',attachments:[]};supplement.triggerEvent=()=>{};
 supplement.open();supplement.save();assert(!supplement.data.expanded);assert.equal(saveCalls,0,'unchanged supplement does not write');supplement.open();supplement.onNoteInput({detail:{value:'draft'}});supplement.close();supplement.open();assert.equal(supplement.data.draftNote,'draft','closing preserves editing draft');supplement.save();await tick();supplement.onNoteInput({detail:{value:'late'}});assert.equal(supplement.data.draftNote,'draft','input frozen during write');supplement.save();assert.equal(saveCalls,1);resolveSave({success:true,data:{optional_note:'draft',attachments:[]}});await tick();assert(!supplement.data.expanded);supplement.properties.entityId='other';supplement.properties.note='next';supplement.open();assert.equal(supplement.data.draftNote,'next','another record cannot inherit draft');
 let detailReads=0;const review=instance(load('pages/review/index.js',n=>n.includes('trade-service')?{getPeriodDetail:()=>{detailReads++;return Promise.resolve({success:true,data:{items:[]}});}}:base(n),{wx,getApp:()=>app}));review.data.summary={plannedCount:0,impulsiveCount:0,reviewedCount:0,regretCount:0};review.openMetricDetail(event('metric','planned'));assert.equal(detailReads,0,'zero metric has no empty detour');review.data.detailOpen=true;review.openDetailRecord(event('id','a&b'));assert(review.data.detailOpen,'return destination retains metric sheet');assert(nav.pop().endsWith('a%26b'));
 const assetHistory=instance(load('pages/asset-history/index.js',n=>n.includes('asset-service')?{list:o=>{reads++;return Promise.resolve(reads===1?{list:[{key:'[\"HK\",\"stock\",\"0700\"]'}],hasMore:true,nextCursor:'next'}:{list:[{key:'[\"US\",\"stock\",\"VST\"]'}],hasMore:false,nextCursor:null});}}:{}, {wx,getApp:()=>app}));
 assetHistory._aliasVersion=0;assetHistory.data.key='["US","stock","RKLB"]';assetHistory.loadAliases();await tick();assert.equal(reads,2,'ineligible page cannot hide later compatible aliases');assert.equal(assetHistory.data.aliasItems.length,1);assert(assetHistory.data.aliasItems[0].key.includes('VST'));
 const tokens=fs.readFileSync('miniprogram/styles/variables.wxss','utf8');assert(tokens.includes('page, .ui-portal'),'detached portals define their own design tokens');
 for(const file of ['pages/review/index.wxml','pages/asset-history/index.wxml','components/optional-supplement/index.wxml'])assert(fs.readFileSync('miniprogram/'+file,'utf8').includes('ui-portal'));
 console.log('Refinement flows: one-tap symbol, direct single confirmation, lazy sheet/cache/empty state, editor draft/no-op/frozen save, zero metric and preserved review context passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
